### PR TITLE
Enabling Azure Active Directory OAuth2 provider

### PR DESCRIPTION
**Pull request by gbablani**
Added support for Azure Active Directory as an Idp in OAuth2\Clients. Added a sample app as well

### CODE REVIEW

**Comment by AArnott** [comment]
@gbablani Is this pull request still current, in light of the fixes you added to the v4.3 branch?

**Comment by gbablani** [comment]
No its not. I need to make the same changes to this one
G

Sent from my Windows Phone

**Comment by AArnott** [comment]
OK, I've just merged v4.3 into master and fixed the build breaks around your Azure AD submission in the v4.3 branch. Please review what's now in master to see if there is any more work required.

**Comment by gbablani** [comment]
Thanks the changes look good and the samples in dotneyopenauthappblock work in both versions

As you are undoubtedly aware the master branch has deprecated RequestAuthentication method which breaks any app generated using vs2012 templates.

P.S : you mention my changes broke the 4.3 build. I did a full build before submitting. Can you share what I broke?

Thanks
Girish

Sent from my Windows Phone

**Comment by AArnott** [comment]
Thanks for verifying that they work in both branches.
I'm still thinking about how to salvage the VS2012 project templates. We can chat more about that on work email.

Regarding the build breaks, no fault of yours there. You've been meticulous in your pull requests and I appreciate that. The build breaks I referred to were from merging your v4.3 changes to master branch (since I regularly merge release branches back to master). Since DNOA has breaking changes between v4.3 and master (as you know) some of your code needed slight adjustments. I believe you made those adjustments to your 'master' pull request already, but as it was your v4.3 pull request that was being merged into master, I just re-made those adjustments.

**Pull request closed without merging**
