### PR TITLE
Standard web request handler exception details

### PR DESCRIPTION
**Pull request by matejskubic**
Improved error reporting.

Created new exception type as discussed.

### CODE REVIEW

**Comment by NiceYellowEgg** [comment]
Having the detailed responses is really useful to diagnose why certain requests failed; receiving "Status is a duplicate" from Twitter rather than "The remote server returned an error: (403) Forbidden." being one example.
Is there a reason this request hasn't been pulled yet?

**Comment by AArnott** [comment]
Well for one thing, the pull request is against master, when it probably should be targeting v4.3, since in master, the `StandardWebRequestHandler` is gone.
But I can redirect to v4.3, no problem. I'll look into it.

**Comment by AArnott** [comment]
I've prepared the merged version of this in the v4.3 branch, but I hesitate because it's technically a backward breaking change, and it seems unnecessary. For instance, with this code change, the error response stream is guaranteed to have been read and closed before the hosting application catches the exception. Before, that would only happen if verbose logging was enabled.

The reason I say this pull request seems unnecessary is because the exception that was thrown before already carried the web response and the host could read it just as you're doing here.

Am I missing something?

**Comment by NiceYellowEgg** [comment]
Thanks for looking into this.  Yes the web response is captured in the protocol exception, but the information is very limited - 403 Forbidden, 401 Unauthorised.  What can't be accessed is the more detailed response body such as "Status is a duplicate", "Status is over 140 characters".  As you say, this is only currently available when verbose logging is enabled.
It's this information that would be really useful to the consumer, and so why it could be encapsulated in the protocol exception or a derived exception shown in this pull.

It's also mentioned here:
https://groups.google.com/forum/#!topic/dotnetopenid/NqtWyNj7mO8

**Comment by AArnott** [comment]
Yes, I understand you want to read the error response body. And you can already. DotNetOpenAuth wraps the WebException inside its ProtocolException. So within your ProtocolException catch block, you can look at the InnerException, cast it to WebException, and then acquire the response body stream just as you were doing in this pull request, and read it from outside the DNOA library.

**Comment by NiceYellowEgg** [comment]
Fair enough, that works for me!  Thanks for looking at this request :)

**Pull request closed without merging**
