### PR TITLE
Update OAuth2ClientChannel.cs

### PR DESCRIPTION
**Pull request by pengweiqhca**
In China, A product called QQ, it return contentType is "text/html" but the content is QueryString

### CODE REVIEW

**Comment by eduardocampano** [comment]
I'm facing this issue too, where the redirect from the authorization server back to the client is making the browser do a request with the content type text/html and this class is generating a ProtocolException

**Comment by AArnott** [comment]
@eduardocampano What you describe doesn't sound like this issue. The HTTP headers browsers send to web servers aren't manipulated by redirect headers. And a browser suggesting it supports a content type of text/html sounds perfectly normal.

**Comment by AArnott** [comment]
@pengweiqhca Thanks, but DNOA doesn't make a habit of adding handling for broken remote servers. QQ should fix their bug.

**Comment by eduardocampano** [comment]
@AArnott Thanks, I figure the issue later, not a DNOA issue. I like the library, but I personally found DNOA hard to debug as packages do not include symbols and aren't also available on symbolsource.

**Comment by AArnott** [comment]
Actually all DNOA releases for the last 2-3 years _are_ available on symbolsource. We have symbols and source code uploaded there.

**Comment by eduardocampano** [comment]
Oh, you're completely right, it was a problem in my VS settings for symbolsource. It works perfect, thank you.

**Pull request closed without merging**
