### PR TITLE
OAuth2 Example Fixes

### LINKED ISSUE #332: Unable run sample of OAuthClient
After compile all source code of project, and I get the error below when I use OAuthClient login in with facebook:
I don't know it is the issue or which config I'm incorrect.
I running with VS2013 and chrome.
## Error

Attempt by method 'DotNetOpenAuth.OAuth2.WebServerClient+<PrepareRequestUserAuthorizationAsync>d__3.MoveNext()' to access method 'System.Collections.Generic.List`1<System.__Canon>..ctor()' failed.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.MethodAccessException: Attempt by method 'DotNetOpenAuth.OAuth2.WebServerClient+<PrepareRequestUserAuthorizationAsync>d__3.MoveNext()' to access method 'System.Collections.Generic.List`1<System.__Canon>..ctor()' failed.

Source Error: 

```
Line 106:           // verifiable for the same user/session.
Line 107:           // If the host is implementing the authorization tracker though, they're handling this protection themselves.
Line 108:           var cookies = new List<CookieHeaderValue>();
Line 109:           if (this.AuthorizationTracker == null) {
Line 110:               string xsrfKey = MessagingUtilities.GetNonCryptoRandomDataAsBase64(16, useWeb64: true);
```

Source File: c:\workspace\demo\DotNetOpenAuth\src\DotNetOpenAuth.OAuth2.Client\OAuth2\WebServerClient.cs    Line: 108 

Stack Trace: 

```
[MethodAccessException: Attempt by method 'DotNetOpenAuth.OAuth2.WebServerClient+<PrepareRequestUserAuthorizationAsync>d__3.MoveNext()' to access method 'System.Collections.Generic.List`1<System.__Canon>..ctor()' failed.]
   DotNetOpenAuth.OAuth2.<PrepareRequestUserAuthorizationAsync>d__3.MoveNext() in c:\workspace\demo\DotNetOpenAuth\src\DotNetOpenAuth.OAuth2.Client\OAuth2\WebServerClient.cs:108
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +144
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +84
   System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() +49
   OAuthClient.<<Page_Load>b__0>d__1.MoveNext() in c:\workspace\demo\DotNetOpenAuth\samples\OAuthClient\Facebook.aspx.cs:28
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +144
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +84
   System.Web.UI.<ExecuteTasksAsync>d__0.MoveNext() +507
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +144
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +84
   System.Web.UI.<ProcessRequestAsync>d__2c.MoveNext() +1145
```

### LINKED ISSUE #349: MVC5 Web.Config assembly reference versions incorrect
Samples\OAuth2\OAuthAuthorizationServer\Views\Web.config reference MVC version 3 instead of MVC version 5 which is the version used in the project references.   

ViewPage<TModel> winds up compiling as a non generic ViewPage.

Pull request coming.

### LINKED ISSUE #351: OAuthAuthorizationServer Anonymous Authentication Not Enabled
If running the example in IIS or IIS Express, anonymous authentication must be enabled for the example to work.  Additionally, the port number specified is not the same as the one used for the asp.net development server.

### LINKED ISSUE #352: Samples OAuth2ProtectedWebApi wrong version of Razor referenced in web.config
The web.config in the views folder references Razor version 2.0 while the project references razor 3.0.   Application does not start as a result.

### LINKED ISSUE #355: Response.ContentType not set when AsActionResult is being used
In the OAuth2 sample  OAuthAuthoriztionServer.Controllers.OAuthController,  HttpResponseMessages are converted to ActionResults using the extension method AsActionResult.  The ActionResult alone does not set the response content type.   The call to AsActionResult must be preceded by:

```
Response.ContentType=request.Content.Headers.ContentType.ToString();
```

A commit to my pull request will be forthcoming

### PR DESCRIPTION
**Pull request by rcollette**
resolves #349 
resolves #351 
resolves #352 
resolves #332 
resolves #355

### CODE REVIEW

**Comment by rcollette** [comment]
I got the latest version of Master and merged the files except for the lines that had my changes using BeyondCompare.   I'm looking at the diff and it is still highlighting lines despite the fact that I didn't even open it in visual studio after the merge.   It looks like the tabs or something else in the line beginnings may be different but I can't tell what.

I'm using TortoiseGit.  Unless there is some setting you are aware of that is causing this, I don't have any more time I can spend chasing down a formatting issue that has nothing to do with how the code runs.   If it were me, the formatting would have less priority than code that doesn't actually run in the first place.

**Comment by rcollette** [comment]
I've gotten the tabs fixed.   Beyond compare had been set to ignore insignificant white space.

**Comment by DavidChristiansen** [comment]
Are you able to change this PR to the develop branch?

**Comment by rcollette** [comment]
Maybe late Monday.   I'll be traveling to CES. :)

**Comment by DavidChristiansen** [comment]
Thanks Richard, I hope it's possible to retarget a PR.  All active development will be on develop going forward.

**Comment by DavidChristiansen** [comment]
No need to do this now Richard, I've done it myself

**Comment by rcollette** [comment]
Thank you.   Missed my flight this a.m. and was about to start on it at the airport.

**Pull request closed without merging**
