### PR TITLE
Pure .Net 4.0 build

### PR DESCRIPTION
**Pull request by NN---**
log4net compiled from https://github.com/apache/log4net but uses only .Net 4.0 assemblies.
No 2.0 assemblies.

Use command line: msbuild build.proj /p:Configuration=Release /p:TargetFrameworkVersion=v4.0 /tv:4.0

### CODE REVIEW

**Comment by AArnott** [comment]
I'm not going to be moving DNOA to be exclusively to CLR 4 for the forseeable future.

**Comment by NN---** [comment]
There is no problems for this.
If you don't specify TargetFrameworkVersion=v4.0 , you still use the CLR 2.0.

Perhaps other solution, what about adding a special project for this , like DotNetOpenAuth-4.0.csproj ?

**Comment by AArnott** [comment]
Ah, I see.  log4net.dll for CLR4 goes into its own directory.

**Comment by NN---** [comment]
Of course I don't want to make impossible compiling for .Net 2.0.
It just I need a pure compilation for 2.0 and for 4.0 , but no mix.

**Pull request closed without merging**
